### ISSUE TITLE
Adjust to the new repo name `aspera-browser-sdk-js` and new package name `@ibm-aspera/browser-sdk`

### ISSUE THREAD

**Issue by gegles** [IBM/aspera-browser-sdk-js#38]
Refactor the code base internally, in the docs, package names, etc... to reflect the new name: "Aspera Browser SDK" in Javascript

**Comment by gegles** [comment]
@dabrad26, any ETA/progress on this? Thx!

**Comment by dabrad26** [comment]
@dwosk is this published?  I tried this naming but get a 404


```
david@Davids-Work-Mac aspera-starter % npm install --save @ibm-aspera/browser-sdk-js
npm ERR! code E404
```


Or is under a different namespace?

**Comment by dabrad26** [comment]
PR open.  Deprecated Desktop SDK JS.  This means it will warn and show deprecated in NPM but not deleted.

![Screenshot 2024-10-22 at 15 31 29](https://github.com/user-attachments/assets/c589a237-d3d8-4963-9b53-fa1a843e3de6)

**Comment by dabrad26** [comment]
Decided via Slack to not use `-js` as this ticket name implied.  So the second PR removes that -js.

**Comment by dabrad26** [comment]
Internal products migrated; this is now live on NPM as well. Closing as complete.
